name: CI/CD for PHP Project

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.6'

      - name: Instalar dependencias
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist

      - name: Ejecutar pruebas con PHPUnit
        run: vendor/bin/phpunit

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Notificar a Ferozo para desplegar
        run: |
          export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=~/.ssh/known_hosts"
          git push origin main
