name: CI/CD for PHP Project

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.6'

      - name: Instalar dependencias
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist

      - name: Ejecutar pruebas con PHPUnit
        run: vendor/bin/phpunit

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # - name: Webhook
      #   run: |
      #     curl -n ${{ secrets.WEBHOOK_URL }} \
      #     --header 'Content-Type: application/x-www-form-urlencoded'
      - name: Invoke deployment webhook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
